Перемещаемые вкладки в TdiNotebook
QualitySolution/QSProjects pull request #265
Opened 2021-03-30 07:40 UTC by efimov90

Добавлена реализация перемещения вкладок.
Добавлена пересортировка подчиненных вкладок.
Добавлена пересортировка при попытке положить вкладку между основной и подчиненными вкладками.

2021-03-30 08:01 UTC, Gankov requested changes
Конкретно в коде я не вижу ничего плохого, визуально. И принял бы реквест. Но эти изменения валят 7 тестов. Похоже они ломают работу TdINavigationManager, во многих случаях.

2021-03-30 08:04 UTC, Gankov commented
Возможно кстати в этих же ситуациях ломается и работа самомого TdiNotebook. Просто на ее практически нет тестов. А для NavigationManager я тестов нафигачил, потому что там очень легко поломать работу.

2021-03-30 10:44 UTC, efimov90 commented
> Конкретно в коде я не вижу ничего плохого, визуально. И принял бы реквест. Но эти изменения валят 7 тестов. Похоже они ломают работу TdINavigationManager, во многих случаях.

А где эти тесты? Их нужно править? Отдельный репозиторий?

2021-03-30 12:16 UTC, Gankov commented
> > Конкретно в коде я не вижу ничего плохого, визуально. И принял бы реквест. Но эти изменения валят 7 тестов. Похоже они ломают работу TdINavigationManager, во многих случаях.
> 
> А где эти тесты? Их нужно править? Отдельный репозиторий?

Нет в репозитории библиотеки. Проект QS.LibsTest, вообще если откроешь солюшен то там тесты будут. Честно говоря дума не в самих тестах дело, а в добавленом коде, он по-моему где то с нул референс падает. Хотя может быть и тесты сами надо переделывать.

2021-03-30 12:16 UTC, Gankov commented
http://ci.qsolution.ru/job/QualitySolution/job/QSProjects/job/feature%252FFeature-DragabbleTabs/1/testReport/

2021-03-30 12:36 UTC, efimov90 commented
> QS.LibsTest

Не вижу ничего похожего на QS.LibsTest в репозитории QSProjects, не там смотрю?

2021-03-30 12:46 UTC, Gankov commented
> > QS.LibsTest
> 
> Не вижу ничего похожего на QS.LibsTest в репозитории QSProjects, не там смотрю? Хотелось бы понять на чем падают, в слепую это изучать не очень то удобно.

https://github.com/QualitySolution/QSProjects/tree/master/QS.LibsTest

2021-04-02 11:33 UTC, efimov90 commented
> > > QS.LibsTest
> > 
> > 
> > Не вижу ничего похожего на QS.LibsTest в репозитории QSProjects, не там смотрю? Хотелось бы понять на чем падают, в слепую это изучать не очень то удобно.
> 
> https://github.com/QualitySolution/QSProjects/tree/master/QS.LibsTest

Спасибо, не в том решении искал, в водовозе они не подключены.

2021-04-02 12:35 UTC, efimov90 commented
Тeсты прошли

2021-04-02 12:37 UTC, Gankov approved these changes

2021-04-02 12:37 UTC, merged

2021-04-02 12:42 UTC, Gankov commented
Ок. А как этим пользоваться? С точки зрения пользователя?
Надо в коде где-то дополнительно включать?