Реализован новый диалог смены пароля и ViewModel к нему
QualitySolution/QSProjects pull request #291
Opened 2021-05-06 12:57 UTC by ShubArseniy

Добавил возможность изменять connectionString из QS.Project.DB.Connection

2021-05-06 12:57 UTC, ShubArseniy commented
**Не мержить**

2021-05-07 07:01 UTC, Enzogord commented on QS.Project/Project.DB/Passwords/DatabasePasswordModel.cs
> +            if(!(connection is MySqlConnection)) {
Если принимается DbConnection, то класс должен со всеми его наследниками отработать правильно

2021-05-07 07:07 UTC, ShubArseniy commented on QS.Project/Project.DB/Passwords/DatabasePasswordModel.cs
> +            if(!(connection is MySqlConnection)) {
Он как бы и должен, только для разных баз нужны разные скрипты. По надобности можно метод расширять

2021-05-07 07:11 UTC, Enzogord submitted a review, later dismissed

2021-05-07 07:17 UTC, Gankov requested changes
Ух ну и темку затронули... Реализация клевая, в плане мне понравилось отображение пароля и прочее. Но вся работа с зависимостями должна быть другой. Зависимости должны быть настоящие. Смену пароля надо надо полностью прятать за интерфейс. Текущая реализация не может быть принята, так как она ломает возможность смены пароля на облачном сервисе.
Сейчас пользователь может залогинется 2мя способами напрямую на MySQL сервер и через облачный сервис, а в будущем возможно появятся другие способы. Данная реализация поддерживает только прямое подключение к базе. Потому что вью модель диалога, знает и про конекшен к базе и про базу как таковую. Как раз предложен интерфейс QS.Project/Project.DB/Passwords/IDatabasePasswordModel.cs, но в нем мало смысла, так как он полностью завязан на конкретную реализацию, и не подходит для смены паролей на облачном сервисе, так как в нее передаются конекшены. Кстати думаю логику смены строки конекшена тоже нужно передать этому провайдеру. Так как например для облака, всегда создается временный пользователь, для подклчения к базе, поэтому пользователю в текущем подключении совершенно не имеет смысла менять пароль. И вот здесь самое сложное. мы уже налепили кучу разрозненных классов, переписывая, части библиотеки на новый лад. В идеале  нам бы надо придти к тому что будет какой то простой, понятный механизм, в виде какого нибудь MySQLProvider и соотвествующего интерфейса, который будет скрывать логику конкретной БД, по работе с пользователями и входом. У нас уже есть MySQLProvider но он вообще тянет древние не нужные совершенно методы. В текущем виде он под удаление. И есть https://github.com/QualitySolution/QSProjects/blob/ed006ba2cbedb7f520282af0cc3690952a1b1d37/QS.Project/Project.Repositories/MySQLUserRepository.cs который в целом частично реализует необходимую логику. В общем надо подумать как это сделать красиво.

2021-05-07 08:18 UTC, ShubArseniy commented on QS.Project.Gtk/ChangePassword.Views/ChangePasswordView.cs
> +                        buttonOK.Sensitive = viewModel.CanSave;
Это диалог, из-за этого кнопки там обычные

2021-05-07 08:18 UTC, ShubArseniy commented on QS.Project.Gtk/ChangePassword.Views/ChangePasswordView.cs
> +                        buttonOK.Sensitive = viewModel.CanSave;
Для паролей придётся написать конвертер, мне кажется это лишнее

2021-05-07 08:20 UTC, Gankov commented on QS.Project.Gtk/ChangePassword.Views/ChangePasswordView.cs
> +                        buttonOK.Sensitive = viewModel.CanSave;
Ну ок.

2021-05-07 10:06 UTC, Gankov approved these changes

2021-05-07 10:13 UTC, Enzogord approved these changes

2021-05-07 10:16 UTC, Gankov commented
Мержим?

2021-05-07 10:18 UTC, merged