Рефакторинг связанный с модулем обновлений и создания базы
QualitySolution/QSProjects pull request #319
Opened 2021-07-07 13:59 UTC by Gankov

Главная цель рефекторинга была запуск инеграционных тестов для прогона скриптов обновления базы. Как на клиентских образцах баз, так и на чистых. 
Так как тесты уже реализованы на dotnet. Начал перевод некоторых классов на библиотеки dotnet.

Изменено пространство имен у интерфейса IInteractiveService.

2021-07-09 07:38 UTC, ShubArseniy commented on QSProjects.dotnet.sln.DotSettings.user
> +&lt;/SessionState&gt;</s:String></wpf:ResourceDictionary>
Это не нужно наверно

2021-07-09 07:38 UTC, ShubArseniy commented on QS.Updater.Core/DBScripts/Controllers/UserCreateDbController.cs
> +				bool success = createMOdel.RunCreation(server, dbname, login, password);
createM**O**del

2021-07-09 07:38 UTC, ShubArseniy commented on QS.Project.Gtk/Navigation/AutofacViewModelsGtkPageFactory.cs
> +		public AutofacViewModelsGtkPageFactory(ILifetimeScope container)
Тогда Container переименовать наверно надо

2021-07-09 10:08 UTC, Gankov commented on QSProjects.dotnet.sln.DotSettings.user
> +&lt;/SessionState&gt;</s:String></wpf:ResourceDictionary>
ок.

2021-07-09 10:10 UTC, Gankov commented on QS.Updater.Core/DBScripts/Controllers/UserCreateDbController.cs
> +				bool success = createMOdel.RunCreation(server, dbname, login, password);
Спасибо.

2021-07-09 10:15 UTC, Gankov commented on QS.Project.Gtk/Navigation/AutofacViewModelsGtkPageFactory.cs
> +		public AutofacViewModelsGtkPageFactory(ILifetimeScope container)
Думаю лучше нет. ибо как выяснилось, Все что относится к резольвингу в интерфейсе IContainer на самом деле относится к интерфейсу ILifetimeScope который он наследует. И то и то контейнеры.

2021-07-09 10:40 UTC, ShubArseniy submitted a review, later dismissed

2021-07-09 10:54 UTC, Enzogord requested changes

2021-07-09 10:54 UTC, Enzogord commented on QS.Updater.Core/DBScripts/Controllers/IDbCreateController.cs
> +		bool BaseExistDropIt(string dbname);
Не логичное название функции, она дропает базу? или проверяет можно ли дропнуть базу? 
Если дропает, то предлагаю название DropDatabaseIfExists

2021-07-09 11:17 UTC, Gankov commented on QS.Updater.Core/DBScripts/Controllers/IDbCreateController.cs
> +		bool BaseExistDropIt(string dbname);
Наверное не логичное. Предложи.
Этот метод у контролера вызывает model создания базы. Модель этим методом спрашивает у контролера нужно ли дропать базу, потому что она существует. Вызывается в тот момент когда модель обнаруживает что база существует.
В том контролере который представлен в библиотеках, контролер спросит у пользователя. В том контролере который в тестах используется, контролер ответит что дропай в любом случае. 
Код контролера в тестах https://github.com/QualitySolution/Workwear/blob/90c20b3e53c293f01c43f5fce9b9328dbc98cd94/Workwear.Test.Sql/Controllers/TestingCreateDbController.cs#L42

2021-07-12 06:15 UTC, ShubArseniy commented on QS.Updater.Core/DBScripts/Controllers/IDbCreateController.cs
> +		bool BaseExistDropIt(string dbname);
Например можно NeedDropDatabaseIfExists

2021-07-12 06:50 UTC, ShubArseniy commented
ПР в мастер идёт? Если да, то надо бы его мержить быстрее. Ревью от Вадима можно не ждать, он в отпуск ушёл

2021-07-12 06:52 UTC, Gankov commented on QS.Updater.Core/DBScripts/Controllers/IDbCreateController.cs
> +		bool BaseExistDropIt(string dbname);
Если так понятнее. Хорошо.

2021-07-12 06:52 UTC, Gankov commented
Все тогда мержу.

2021-07-12 06:53 UTC, ShubArseniy approved these changes

2021-07-12 06:54 UTC, merged