Открытие диалогов из EVME с помощью IEntitySelector
QualitySolution/QSProjects pull request #345
Opened 2021-08-24 06:47 UTC by kozlov-d

Чтобы по нажатию "открыть" в EVME была возможность открыть новые диалоги, которые не работают с orm, решили сделать таким образом

2021-08-24 07:08 UTC, ShubArseniy commented on QS.Project/Project.Journal/FilterableMultipleEntityJournalViewModelBase.cs
> +		}
Если не собираешься реализовывать, то ставь NotSupported

2021-08-24 07:16 UTC, Enzogord requested changes

2021-08-24 07:16 UTC, Enzogord commented on QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
> +			}
Открытие через Entry не делает новый диалог зависимым, поэтому считаю что журнал сам может открыть его. И для этого не требуется кидаться вкладками, можно просто использовать метод void Open(node), и журнал сам может сделать остальное.
Этот способ и обсуждали как раз, из-за чего захотел от него отказаться?

2021-08-24 07:16 UTC, Enzogord commented on QS.Project/Project.Journal/EntitySelector/IEntitySelector.cs
> +		bool CanOpen();
А как журнал узнает что именно он должен мочь открыть? Считаю что туда надо передавать ноду.

2021-08-24 07:21 UTC, Enzogord commented
И есть ошибки:

TestApp/JournalViewModels/DocumentsJournalViewModel.cs(9,15): error CS0534: 'DocumentsJournalViewModel' does not implement inherited abstract member 'EntitiesJournalViewModelBase<DocumentJournalNode>.CanOpen()' [/var/lib/jenkins/workspace/ualitySolution_QSProjects_PR-345/QSProjects/QS.LibsTest/QS.LibsTest.csproj]
  TestApp/JournalViewModels/DocumentsJournalViewModel.cs(9,15): error CS0534: 'DocumentsJournalViewModel' does not implement inherited abstract member 'EntitiesJournalViewModelBase<DocumentJournalNode>.GetTabToOpen(JournalEntityNodeBase)' [/var/lib/jenkins/workspace/ualitySolution_QSProjects_PR-345/QSProjects/QS.LibsTest/QS.LibsTest.csproj]

2021-08-24 07:24 UTC, kozlov-d commented on QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
> +			}
Изначально пытался в open(node) сделать открытие через mytab.TabParent.AddTab или вроде того, выше в методе selectEntity таким же образом используется. Но у entitySelector нет TabParent до того, как он сам не будет открыт через AddTab (или другие подобные методы). Сейчас правда понял, что можно было попробовать с NavigationManager.
Присваивать TabParent после создания селектора показалось плохим решением, потому решил вернуть просто вкладку для открытия, т.к. evme уже занимается открытием вкладок, а вот присвоение tabParent уже идет где то в TdiNotebook

2021-08-24 07:36 UTC, kozlov-d commented on QS.Project/Project.Journal/EntitySelector/IEntitySelector.cs
> +		bool CanOpen();
И будет на основе того, null нода или нет возвращать значение? Что тогда будет с multipleEntityJournal, нода есть, по типу это тоже JENodeBase, значит может что то открыть, а какая будет реализация у метода открытия(или как сейчас, вовзрата вкладки)? Сейчас по сути этот метод возвращает есть ли реализация для метода открытия, или нет. Что я упустил - стоило добавить в EVME проверку ноды на NULL, но кнопка открыть сама по себе неактивна, если subject == null

2021-08-24 07:37 UTC, kozlov-d commented on QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
> +			}
Либо можно передавать TabParent в метод открытия

2021-08-24 08:14 UTC, Enzogord commented on QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
> +			}
Вот пример:
EntitiesJournalViewModelBase.cs:269
TabParent.OpenTab(() => foundDocumentConfig.GetOpenEntityDlgFunction().Invoke(selectedNode), this);
Рядом есть проверка которую можно использовать для CanOpen

Так и не понял что мешает использовать это, можешь подробнее описать?

2021-08-24 08:28 UTC, kozlov-d commented on QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
> +			}
```C#
		public void OpenSelectDialog(string newTabTitle = null)
		{
			if(entitySelector != null) {
				MyTab.TabParent.SwitchOnTab(entitySelector);
				return;
			}

			entitySelector = entitySelectorFactory.CreateSelector();
			entitySelector.OnEntitySelectedResult += JournalViewModel_OnEntitySelectedResult;
			entitySelector.TabClosed += EntitySelector_TabClosed;
			MyTab.TabParent.AddSlaveTab(MyTab, entitySelector);
		}

		void EntitySelector_TabClosed(object sender, EventArgs e)
		{
			entitySelector = null;
		}

```

entitySelector зануляется при закрытии вкладки. TabParent != null у EntitySelector только после MyTab.TabParent.AddSlaveTab(MyTab, entitySelector); Внутри метода open(aka getTabToOpen), когда я его вызываю, у моего селектора, который я отдельно создаю для этого, TabParent == null. Могу сделать одним из этих способов - устанавливая tabParent и потом вызывая, open(node), либо вызывая open(node, tabParent)
```C#
		entitySelector.TabParent = MyTab.TabParent;
		entitySelector.Open(selectedNode, MyTab.TabParent);
```

```EntitiesJournalViewModelBase.cs:269```
В момент выполнения этого метода TabParent будет у журнала, потому что это journalActions, доступные при открытом журнале

2021-08-24 08:39 UTC, Enzogord commented on QS.Project.Gtk/Widgets.GtkUI/EntityViewModelEntry.cs
> +			}
Понял, значит надо попробовать через NavigationManager. Не надо новые интерфейсы с TDI создавать.

2021-08-24 08:41 UTC, Gankov approved these changes
Я эти модули не использую, если вам подходит то ок.

2021-08-24 09:04 UTC, Gankov commented
> И есть ошибки:
> 
> TestApp/JournalViewModels/DocumentsJournalViewModel.cs(9,15): error CS0534: 'DocumentsJournalViewModel' does not implement inherited abstract member 'EntitiesJournalViewModelBase.CanOpen()' [/var/lib/jenkins/workspace/ualitySolution_QSProjects_PR-345/QSProjects/QS.LibsTest/QS.LibsTest.csproj]
> TestApp/JournalViewModels/DocumentsJournalViewModel.cs(9,15): error CS0534: 'DocumentsJournalViewModel' does not implement inherited abstract member 'EntitiesJournalViewModelBase.GetTabToOpen(JournalEntityNodeBase)' [/var/lib/jenkins/workspace/ualitySolution_QSProjects_PR-345/QSProjects/QS.LibsTest/QS.LibsTest.csproj]

По-моему этот класс сейчас не в одном тесте не используется и его можно удалить.

2021-08-27 07:01 UTC, Gankov submitted a review, later dismissed

2021-08-31 10:15 UTC, Enzogord requested changes

2021-08-31 10:40 UTC, ShubArseniy commented on QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
> +		}
Тут эксепшена не будет на словаре? Разве все типы зарегистрированы?

2021-08-31 10:43 UTC, kozlov-d commented on QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
> +		}
В simple и single как я понимаю регистрация автоматически происходит, в multiple вручную - но если что то не зарегистрировать оно разве будет работать в принципе (JournalActions и т.д.)? Я как раз из JA же взял это

2021-08-31 10:53 UTC, Enzogord commented on QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
> +		}
Лучше все же проверить это, вернуть false если что-то не так ничего не стоит.

2021-08-31 10:54 UTC, Enzogord commented on QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
> +				config.EntityDocumentConfigurations.FirstOrDefault(x => x.IsIdentified((TNode)node));
И тут конфиг проверить, если его нет то кидать InvalidOperation

2021-08-31 11:55 UTC, Enzogord approved these changes

2021-08-31 12:37 UTC, Gankov approved these changes

2021-09-01 13:29 UTC, merged