Для истории логов
QualitySolution/QSProjects pull request #400
Opened 2022-01-28 13:20 UTC by FirstIlyasIT

2022-02-08 14:24 UTC, Gankov requested changes

2022-02-09 06:55 UTC, Gankov commented on Binding/Gamma.Binding/Widgets/yListComboBox.cs
> +					OnEnumItemSelected ();
Зачем сделано изменение в этом месте?

2022-02-09 06:56 UTC, FirstIlyasIT commented on Binding/Gamma.Binding/Widgets/yListComboBox.cs
> +					OnEnumItemSelected ();
Делал значение по умолчанию, потом нашёл другой comboList и откатил изменения

2022-02-24 10:42 UTC, Gankov approved these changes

2022-02-24 10:42 UTC, Gankov commented on QS.HistoryLog.Desktop/ViewModels/HistoryViewModel.cs
> +			logger.Info(NumberToTextRus.FormatCase(changedEntities.Count, "Загружено изменение {0}{1} объект.", "Загружено изменение {0}{1} объекта.", "Загружено изменение {0}{1} объектов.", ""));
Зачем в этой строке {1} не пойму.

2022-02-24 11:02 UTC, ShubArseniy commented on QS.HistoryLog.Gtk/QS.HistoryLog.Gtk.sln
> +Global
Зачем нужен sln файл для одного проекта?

2022-02-24 11:11 UTC, Gankov commented on QS.HistoryLog.Desktop/ViewModels/HistoryViewModel.cs
> +			}
Да или вообще заменить на атрибут https://github.com/QualitySolution/QSProjects/wiki/%D0%9F%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D1%81-INotifyPropertyChanged#%D0%9A%D0%B0%D1%81%D0%BA%D0%B0%D0%B4%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2

2022-02-24 11:12 UTC, Gankov commented on QS.HistoryLog.Gtk/QS.HistoryLog.Gtk.sln
> +Global
Не нужен, Ильяс надо удалить.

2022-02-25 07:55 UTC, ShubArseniy commented on QS.HistoryLog.Desktop/QS.HistoryLog.Desktop.csproj
> +  </ItemGroup>
```suggestion
```

2022-02-25 08:37 UTC, Gankov approved these changes

2022-02-25 08:37 UTC, Gankov commented
Есть еще замечания? Или можем мержить?

2022-02-25 08:40 UTC, ShubArseniy approved these changes

2022-02-25 11:40 UTC, Gankov commented
Нашли баги будем исправлять.

2022-03-03 14:09 UTC, Enzogord approved these changes

2022-03-04 07:28 UTC, Gankov approved these changes

2022-03-04 07:28 UTC, Gankov commented on QS.HistoryLog.Gtk/Views/HistoryView.cs
> +	public partial class HistoryView : DialogViewBase<HistoryViewModel>
Давай пока оставим Так, пока нет другого View, потому что не ясно насколько в нем будет реализовано такое же переключение на сегодня, 7 дней и т.п. Может быть его там не будет.

2022-03-04 07:28 UTC, merged