Перенос ExceptionHelper из Reports в Utilities
QualitySolution/QSProjects pull request #570
Opened 2023-12-26 16:28 UTC by Enzogord

2023-12-27 08:13 UTC, Gankov requested changes
Все отлично, только давай перенесем в QS.Utilities.Debug
мне кажется это логичнее.

2024-04-12 13:38 UTC, Gankov approved these changes

2024-04-12 13:41 UTC, Gankov approved these changes

2024-04-12 13:42 UTC, Gankov submitted a review, later dismissed

2024-04-12 13:52 UTC, Enzogord commented
Изменения перенесены в https://github.com/QualitySolution/QSProjects/pull/585

2024-04-12 13:52 UTC, closed without merging