Изменения по Async UoW и прочее связанное с ним
QualitySolution/QSProjects pull request #586
Opened 2024-04-16 13:19 UTC by Enzogord

Коротко, изменены: UoW, UoWTracker, Валидатор, Статические сервисы, удален UnitOfWorkFactory, добавлены методы настройки подключения к бд и настройки регистраций в контейнере.

Более подробно описано тут: [Настройка приложения с контейнером DI](https://github.com/QualitySolution/QSProjects/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F-%D1%81-%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%B9%D0%BD%D0%B5%D1%80%D0%BE%D0%BC-DI)

Продолжение ПРа: https://github.com/QualitySolution/QSProjects/pull/571

2024-04-17 14:29 UTC, Gankov approved these changes

2024-04-17 14:29 UTC, Gankov commented on QS.Project.Desktop/QS.Project.Desktop.csproj
> +      <ProjectReference Include="..\..\Gtk.DataBindings\System.Data.Bindings\System.Data.Bindings.csproj" />
Это что еще такое? Мы выпилили эту библиотеку.

2024-04-17 14:29 UTC, Gankov commented on QS.Project/QS.Project.csproj
> +    <ProjectReference Include="..\..\Gtk.DataBindings\System.Data.Bindings\System.Data.Bindings.csproj" />
Удалено!!

2024-04-17 14:29 UTC, Gankov commented on QS.Project/QS.Project.csproj
> +    <Compile Remove="Project.Domain\IEntityPermission.cs" />
Зачем эта строчка? Если файл не надо компилить, может его вообще удалить?

2024-04-17 17:38 UTC, Gankov requested changes

2024-04-17 17:38 UTC, Gankov commented on QS.Project.Core/Deletion/DeleteCore.cs
> +		public DeleteCore(DeleteConfiguration configuration, IUnitOfWorkFactory uowFactory, IUnitOfWork uow = null, DbConnection connection = null)
Если мы соседним параметром передаем сам uow. Почему в этой ситуации передача фабрики является обязательной?

2024-04-19 06:40 UTC, Enzogord commented on QS.Project.Core/Deletion/DeleteCore.cs
> +		public DeleteCore(DeleteConfiguration configuration, IUnitOfWorkFactory uowFactory, IUnitOfWork uow = null, DbConnection connection = null)
Потому что, если uow не передан то он автоматом создается при первом обращении к DeleteCore.UoW.

2024-04-19 07:53 UTC, Gankov commented on QS.Project.Core/Deletion/DeleteCore.cs
> +		public DeleteCore(DeleteConfiguration configuration, IUnitOfWorkFactory uowFactory, IUnitOfWork uow = null, DbConnection connection = null)
Так если не передан, то да. А вот если передан? ну нельзя же требовать ненужное? Сейчас нет возможности не передавать фабрику. Если я предаю uow.

2024-07-04 06:41 UTC, Gankov approved these changes

2024-12-12 08:38 UTC, Gankov commented
Все изменения из этого пул реквеста залиты сначала в QS.Launcher и активно использовались в новой ветке с лаунчером, но там было внесено очень много других изменений в библиотеки, что назвать ветку просто лаунчером язык не поворачивается. Изменения пока не готовы полностью для продакешена поэтому перемещены и развиваются в новой ветке develop. Так как мы не осилили отдельно новую конфигурацию из этой ветки, то пулреквест отдельно имеет мало смысла. Думаю зальем его вместе с остальным кодом из develop, когда доведем ее до полностью оттестированной и готовой к использованию.

2024-12-12 08:38 UTC, closed without merging